services:
    cuda_opencv:
        build:
            context: .
            dockerfile: Dockerfile
        image: cuda_tensorflow_opencv:latest
        container_name: cuda_opencv
        environment:
            - NVIDIA_VISIBLE_DEVICES=all # Make all GPUs visible
            - NVIDIA_DRIVER_CAPABILITIES=all # Enable all NVIDIA driver capabilities
        volumes:
            - ./:/app
        network_mode: "host"
        restart: unless-stopped
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu, video, compute, utility]
        # Keep the container running with an interactive command
        tty: true
        stdin_open: true
        command: /bin/bash
